name: Push and pull request
on: [pull_request, push]
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Build
        run: >
          ./gradlew
          --no-daemon
          clean
          :api:assemble
          :api-kt:assemble
          :api:test
          :api-kt:test
          :api:javadoc
          :api-kt:dokkaHtml
        env:
          JAVA_OPTS: '-Xmx4096m'
